<<<<<<< HEAD
# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 
=======
title: GaryStack
email: 3225078214@qq.com

author:
  picture: http://site.hugocarreira.me/assets/img/compressed/hugo.jpg #URL FORMAT
  name: zkj
  location: SDDY
  description: "神"  
  

description: zyf吊打集训队
baseurl: "/"
url: https://garystack.github.io
twitter_username: hugocolombo23
github_username:  GaryStack
github_url: https://github.com/GaryStack/
>>>>>>> 61fe5c569604f5d0cb2079e77442e9a73d12a393

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
